controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_cours:
    path: /cours
    controller: App\Controller\CoursController::index

coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister