controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_Instrument:
    path: /instrument
    controller: App\Controller\InstrumentController::index

app_lister_instrument:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::lister

app_cours:
    path: /cours
    controller: App\Controller\CoursController::index

app_intervention:
    path: /intervention
    controller: App\Controller\InterventionController::index
    
app_eleve:
    path: /eleve
    controller: App\Controller\EleveController::index
