controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_Instrument:
    path: /Instrument
    controller: App\Controller\InstrumentController::index

app_cours:
    path: /cours
    controller: App\Controller\CoursController::index

app_cours_lister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister

app_intervention:
    path: /intervention
    controller: App\Controller\InterventionController::index
    
app_eleve:
    path: /eleve
    controller: App\Controller\EleveController::index

