controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Instrument

app_Instrument:
    path: /instrument
    controller: App\Controller\InstrumentController::index

app_lister_instrument:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::lister

# Cours

app_cours:
    path: /cours
    controller: App\Controller\CoursController::index

app_cours_lister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister

app_cours_consulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulter

# Intervention

app_intervention:
    path: /intervention
    controller: App\Controller\InterventionController::index

app_intervention_lister:
    path: /intervention/lister
    controller: App\Controller\InterventionController::lister

app_intervention_consulter:
    path: /intervention/consulter/{id}
    controller: App\Controller\InterventionController::consulter

#Eleve

app_eleve:
    path: /eleve
    controller: App\Controller\EleveController::index
    
app_eleve_lister:
    path: /eleve/lister
    controller: App\Controller\EleveController::lister
    
app_eleve_consulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulter
