controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Instrument

app_Instrument:
    path: /instrument
    controller: App\Controller\InstrumentController::index

app_lister_instrument:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::lister

app_consulter_instrument:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulter

app_ajouter_instrument:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouter

app_modifier_instrument:
    path: /instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifier

# Cours

app_cours:
    path: /cours
    controller: App\Controller\CoursController::index

app_cours_lister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister

app_cours_consulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulter

app_cours_ajouter:
    path: /cours/ajouter
    controller: App\Controller\CoursController::ajouter

app_cours_modifier:
    path: /cours/modifier/{id}
    controller: App\Controller\CoursController::modifier

app_cours_supprimer:
    path: /cours/supprimer/{id}
    controller: App\Controller\CoursController::supprimer

# Intervention

app_intervention:
    path: /intervention
    controller: App\Controller\InterventionController::index

app_intervention_lister:
    path: /intervention/lister
    controller: App\Controller\InterventionController::lister

app_intervention_consulter:
    path: /intervention/consulter/{id}
    controller: App\Controller\InterventionController::consulter

app_intervention_ajouter:
    path: /intervention/ajouter
    controller: App\Controller\InterventionController::ajouter

app_intervention_modifier:
    path: /intervention/modifier/{id}
    controller: App\Controller\InterventionController::modifier

app_intervention_supprimer:
    path: /intervention/supprimer/{id}
    controller: App\Controller\InterventionController::supprimer

#Eleve

app_eleve:
    path: /eleve
    controller: App\Controller\EleveController::index
    
app_eleve_lister:
    path: /eleve/lister
    controller: App\Controller\EleveController::lister
    
app_eleve_consulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulter
    
app_eleve_ajouter:
    path: /eleve/ajouter
    controller: App\Controller\EleveController::ajouter
    
app_eleve_modifier:
    path: /eleve/modifier/{id}
    controller: App\Controller\EleveController::modifier
    
app_eleve_supprimer:
    path: /eleve/supprimer/{id}
    controller: App\Controller\EleveController::supprimer
