controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_Instrument:
    path: /Instrument
    controller: App\Controller\InstrumentController::index